- bower.json
- client/app/app.js
- client/app/auth/auth.js
- client/app/auth/signin.html
- client/app/auth/signup.html
- client/app/directories/directories.js
- client/app/services/services.js
- client/index.html
* Create and restructure front end file structure
* Structure index and app files
* Move bower file and setup install folder
* Create login and signup pages and auth controller
* Create folders view in index file, add api requests for signin, signup and folders views
> Create and restructure front end

- client/app/app.js
- client/app/auth/auth.js
- client/app/directories/main.html
- client/app/editor/editor.html
- client/app/services/services.js
- client/app/snippets/snippets.html
- client/app/snippets/snippets.js
- client/index.html
> Create main view (folder view)

- client/app/services/fileTree.js
- client/app/snippets/snippets.html
- client/app/snippets/snippets.js
> Add list items on click for folders in snippets, display filePaths in

- client/app/directories/directories.js
- client/app/directories/main.html
> Fix search bar

- .dockerignore
- DockerFile
- Dockerfile
- docker-compose.yml
- package.json
- server/config/routes.js
- server/server.js
> Docker-Compose setup

- client/app/app.js
- client/app/directories/main.html
- client/app/editor/editor.html
- client/app/editor/editor.js
- client/app/services/services.js
- client/app/snippets/favorites.html
- client/app/snippets/snippets.html
- client/app/snippets/snippets.js
- client/styles/style.css
- server/models/snippets.js
- server/models/users.js
Add favorite property to snippet schema
Align breadcrumbs and signout
Add the update snippet functionality
Closes #99 and #104
> Add logout, favorites and update snippet

- client/app/auth/auth.js
- client/app/editor/editor.html
- client/app/editor/editor.js
- client/app/services/fileTree.js
- client/app/services/services.js
- client/app/snippets/snippets.html
- client/app/snippets/snippets.js
- server/config/routes.js
Redirect to main after login
Add favorite functionality and redo addOrUpdate function. Closes #103
Dispatch selected snippet action after adding new snippet
> Add favorite functionality and redo addOrUpdate function

- client/app/auth/auth.js
- client/app/redux/actions.js
- client/app/redux/reducers.js
- client/app/services/services.js
- server/config/routes.js
- server/models/users.js
Add actions and reducer for active user
Change token property
> Add actions and reducer for active user

- server/models/annotations.js
Adds Schema for annotations and basic methods. closes #130.
> Annotation schema

- server/models/annotations.js
Uses correct schema in Annotations
> Fixes mongoose schema creation

- server/models/annotations.js
- server/models/snippets.js
- test/test.js
Adds unit testing for Annotations methods. Fixes Annotation model copypasta.
> Annotation tests

- server/config/routes.js
Adds routes for api/annotations GET POST PUT, and DELETE. adds route for api/snippet/annotations. Also doesn't delete the api/user/snippets route haha... -__-
Closes #147
> Annotation routes

- client/app/app.js
- client/app/auth/auth.js
- client/app/directories/directories.js
- client/app/directories/main.html
- client/app/editor/editor.html
- client/app/redux/actions.js
- client/app/search/search.html
- client/app/search/search.js
- client/app/services/services.js
- client/app/snippets/snippets.html
- client/styles/style.css
- package.json
- server/config/middleware.js
- server/config/routes.js
> Restructure front-end and add search template

- package.json
- server/config/routes.js
- server/models/snippets.js
- server/models/users.js
- test/TestingOutline.txt
- test/test.js
Adds /snippets and Snippets.getPublic method on server side.
> Public snippet route

- client/app/annotations/annotations.html
- client/app/annotations/annotations.js
- client/app/app.js
- client/app/editor/editor.html
- client/app/editor/editor.js
- client/app/services/fileTree.js
- client/app/services/services.js
- client/styles/style.css
- server/config/middleware.js
- server/config/routes.js
- server/models/snippets.js
- server/models/users.js
add username to every snippet instance
> Change snippets model, change token params; add decoding

- client/app/editor/editor.js
- client/app/main/main.html
- client/app/main/main.js
- client/app/services/services.js
- client/index.html
- client/styles/style.css
- server/controllers/userController.js
- server/models/snippets.js
- Add additional checks to eliminate unathorized requests
> Save selected snippet on user model and load it in on start

- client/app/download/download.html
- client/app/editor/editor.html
- client/app/editor/editor.js
- client/app/main/main.html
- client/app/services/services.js
- client/app/snippets/snippets.html
- client/app/snippets/snippets.js
- client/styles/style.css
- server/controllers/userController.js
- Fix bug where you could add snippet with no name
- add fade animation to list items
> Update user's selected snippet in db on update or delete

- client-server/client/app/editor/editor.html
- client-server/client/app/editor/editor.js
- client-server/client/app/main/main.html
- client-server/client/app/main/main.js
- client-server/client/app/search/search.html
- client-server/client/app/services/services.js
- client-server/client/app/snippets/favorites.html
- client-server/client/app/snippets/snippets.html
- client-server/client/styles/style.css
Add different icon to favorites toggle
Fix order change in snippets list and favorites list and fix add snippet button bug
Style Search page and fix bug with editor theme and ui router state change
> Style Search page, fix editor theme, ui router state change and favorites icon toggle

- client-server/client/app/main/main.html
- client-server/client/app/profile/profile.html
- client-server/client/app/profile/profile.js
- client-server/client/app/services/services.js
- client-server/client/app/snippets/snippets.js
- client-server/client/styles/style.css
- user-server/config/routes.js
- user-server/controllers/userController.js
- user-server/models/users.js
Implement password change functionality and fix change username functionality
> Implement password change functionality and fix change username functionality

- client-server/client/app/editor/editor.html
- client-server/client/app/main/main.html
- client-server/client/styles/style.css
Fixes Overlay triggers
Changes sidenav overlay to white.
Fixes jumping editor animation
> Sidenav focusing

- client-server/client/app/app.js
- client-server/client/app/editor/editor.html
- client-server/client/app/editor/editor.js
- client-server/client/app/foldermodal/foldermodal.js
- client-server/client/app/main/main.js
- client-server/client/app/movemodal/moveModal.html
- client-server/client/app/movemodal/moveModal.js
- client-server/client/app/search/search.html
- client-server/client/app/search/search.js
- client-server/client/app/services/fileTree.js
- client-server/client/app/snippets/snippets.html
- client-server/client/app/snippets/snippets.js
- package.json
Fix public/private toggle and notes
Add focusOn on edit, new snippet and search
Create getAllFolderPaths function and move modal view
> Add move snippet functionality

- client-server/client/app/app.js
- client-server/client/app/editor/editor.js
- client-server/client/app/editor/editorModal.html
- client-server/client/app/public/public.html
- client-server/client/app/public/public.js
- test/userSpec.js
- user-server/controllers/userController.js
- user-server/models/users.js
* Fix test objects and change username to be required
* Redirect users to public if tried to access restricted url
> Fix github username update

- client-server/client/app/editor/editor.html
- client-server/client/app/editor/editor.js
- client-server/client/app/main/main.html
- client-server/client/app/profile/profile.html
- client-server/client/app/search/search.html
- client-server/client/app/snippets/favorites.html
- client-server/client/app/snippets/snippets.html
- client-server/client/styles/style.css
- client-server/server.js
Fix tooltip positions, change color of public snippets
Fixes #245
> Restructure styles file, remove waves-teal, fix search routing issue

- client-server/client/app/editor/editor.html
- client-server/client/app/editor/editor.js
- files-server/config/utils.js
- files-server/controllers/snippetsController.js
Adds base 62 encoding for hex number shortening
> Share url shorten
